common:
mainnet:
  schain:
    disk_size_bytes: 2000000000000
testnet:
  schain:
    disk_size_bytes: 200000000000
qanet:
  schain:
    disk_size_bytes: 200000000000
devnet:
  schain:
    disk_size_bytes: 80000000000
